--- #YAML:1.0
name:                Template-Plugin-Filter-VisualTruncate
version:             0.04
abstract:            Filter Plugin for trimming text by the number of the columns of terminals and mobile phones.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Encode:                        2.23
    Template:                      0
    Test::Base:                    0
    Test::More:                    0
    Text::CharWidth:               0.04
    Text::VisualWidth:             0.01
    UNIVERSAL::require:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - bokutin <bokutin@cpan.org>
